### ISSUE TITLE
Notification is sent even for own messages

### ISSUE THREAD

**Issue by michaelz** [FSMaxB/native-teams-notifications#1]
Hi !

Thank you for this extension.

Currently, the notification is sent for basically any action on teams.
Is there a way to filter the message to show only important notifications ?

**Comment by FSMaxB** [comment]
I'm currently working on a way to filter what notifications to display. I haven't yet found a way to know if a message is from yourself or from somebody else though.

My plan is to have a blacklist of People/Channels that shouldn't trigger a notification, then you could put your own name in there.

As far as I remember there is a way to find out if a message is marked as important from the JSON that I receive, so this should be doable.

All of the above depends on me having time to implement them though.

**Comment by FSMaxB** [comment]
To be more specific:

The way this extension works is by intercepting Microsofts push notifications and extracting information from the JSON that they contain.

The information I currently have access to is:
* The content of the message
* The sender
* The ID of the conversation (but not the name of the Team/Channel)
* A bunch of other stuff that I haven't fully reverse engineered yet.

**Comment by FSMaxB** [comment]
🎉 This is now implemented on the `conversations`-Branch and will be released once it has been better documented and tested.

You can:
* Ignore conversations (like one chat or one channel in a team)
* Ignore users (yourself)
* Only notify for important messages!

**Comment by FSMaxB** [comment]
This is now implemented in version 0.1.0

**Comment by michaelz** [comment]
Thank you for your work.

I'll try it ASAP.
